### ISSUE TITLE
When/will this be added to wf-plugins-extra

### ISSUE THREAD

**Issue by vollowx** [ammen99/wf-basic-deco#2]
I'm currently using gtk3/4 and qt, non-framework-based applications at the same time, which look really ugly b/c of the different decorations.

I wonder if this will be added into wf-plugins-extra and when if so :rocket:

**Comment by ammen99** [comment]
it is just a demo to show howbit could be done, but I have no plans to continue working on it myself.

**Comment by vollowx** [comment]
That's all right. Anyway thanks for your great work!
